In [2]:
import pandas as pd
import numpy as np
data=pd.read_csv('train.csv')

In [3]:
data

,Unnamed: 0,year,month,day,hour,PM2.5,temperature,pressure,rain,wind_direction,wind_speed
0,0,2013,-37.0,1.0,0.0,4.0,-0.7,102-37,0.0,NNW,4.4
1,1,201-37,-37.0,1.0,1.0,8.0,-1.1,1023.2,0.0,N,NaN
2,2,2013,3.0,1.0,2.0,7.0,-1.1,1023.5,0.0,NNW,5.6
3,3,2013,3.0,1.0,3.0,6.0,-1.4,1024.5,0.0,NW,3.1
4,4,2013,3.0,1.0,4.0,3.0,-2.0,1025.2,0.0,N,2.0
...,...,...,...,...,...,...,...,...,...,...,...
31522,35022,2017,2.0,27.0,6.0,80.0,-0.3,1019.4,0.0,ENE,0.8
31523,35032,2017,2.0,27.0,16.0,75.0,15.9,1014,0.0,SW,2.9
31524,35035,2017,2.0,27.0,19.0,51.0,11.5,1014.1,0.0,SSW,1.0
31525,35042,2017,2.0,28.0,2.0,9.0,8.6,1016,0.0,NNE,0.9
31526,35054,2017,2.0,28.0,14.0,5.0,14.6,1013.3,0.0,N,3.6

No. of NaN values in each column:

In [4]:
data.isna().sum()

Unnamed: 0         0
year              15
month              6
day               20
hour               8
PM2.5             14
temperature       19
pressure          27
rain              12
wind_direction    60
wind_speed        25
dtype: int64

Removing all rows with NaN values:

In [5]:
datanew = data.dropna()

In [6]:
datanew

,Unnamed: 0,year,month,day,hour,PM2.5,temperature,pressure,rain,wind_direction,wind_speed
0,0,2013,-37.0,1.0,0.0,4.0,-0.7,102-37,0.0,NNW,4.4
2,2,2013,3.0,1.0,2.0,7.0,-1.1,1023.5,0.0,NNW,5.6
3,3,2013,3.0,1.0,3.0,6.0,-1.4,1024.5,0.0,NW,3.1
4,4,2013,3.0,1.0,4.0,3.0,-2.0,1025.2,0.0,N,2.0
6,6,2013,3.0,1.0,6.0,3.0,-2.6,1026.5,0.0,NNE,2.5
...,...,...,...,...,...,...,...,...,...,...,...
31522,35022,2017,2.0,27.0,6.0,80.0,-0.3,1019.4,0.0,ENE,0.8
31523,35032,2017,2.0,27.0,16.0,75.0,15.9,1014,0.0,SW,2.9
31524,35035,2017,2.0,27.0,19.0,51.0,11.5,1014.1,0.0,SSW,1.0
31525,35042,2017,2.0,28.0,2.0,9.0,8.6,1016,0.0,NNE,0.9
31526,35054,2017,2.0,28.0,14.0,5.0,14.6,1013.3,0.0,N,3.6

Removing all rows which have non numeric values in the following fields-"year","month","day","hour","PM2.5","temperature","pressure","rain"

In [7]:
for i in ["year","month","day","hour","PM2.5","temperature","pressure","rain","wind_speed"]:
    datanew=datanew[pd.to_numeric(datanew[i], errors='coerce').notnull()]

In [8]:
datanew

,Unnamed: 0,year,month,day,hour,PM2.5,temperature,pressure,rain,wind_direction,wind_speed
2,2,2013,3.0,1.0,2.0,7.0,-1.1,1023.5,0.0,NNW,5.6
3,3,2013,3.0,1.0,3.0,6.0,-1.4,1024.5,0.0,NW,3.1
4,4,2013,3.0,1.0,4.0,3.0,-2.0,1025.2,0.0,N,2.0
6,6,2013,3.0,1.0,6.0,3.0,-2.6,1026.5,0.0,NNE,2.5
7,7,2013,3.0,1.0,7.0,3.0,-1.6,1027.4,0.0,NNW,3.8
...,...,...,...,...,...,...,...,...,...,...,...
31522,35022,2017,2.0,27.0,6.0,80.0,-0.3,1019.4,0.0,ENE,0.8
31523,35032,2017,2.0,27.0,16.0,75.0,15.9,1014,0.0,SW,2.9
31524,35035,2017,2.0,27.0,19.0,51.0,11.5,1014.1,0.0,SSW,1.0
31525,35042,2017,2.0,28.0,2.0,9.0,8.6,1016,0.0,NNE,0.9
31526,35054,2017,2.0,28.0,14.0,5.0,14.6,1013.3,0.0,N,3.6

Describing each column of the dataset-

In [9]:
datanew["year"].describe()

count     31370
unique        5
top        2015
freq       8522
Name: year, dtype: object

In [10]:
#Converting to numeric
col_year = pd.to_numeric(datanew["year"])

In [11]:
col_year

2        2013
3        2013
4        2013
6        2013
7        2013
         ...
31522    2017
31523    2017
31524    2017
31525    2017
31526    2017
Name: year, Length: 31370, dtype: int64

In [12]:
col_year.describe()

count    31370.000000
mean      2014.514345
std          1.103668
min       2013.000000
25%       2014.000000
50%       2015.000000
75%       2015.000000
max       2017.000000
Name: year, dtype: float64

In [13]:
datanew["month"].describe()

count    31370.000000
mean         6.459866
std          3.306088
min          1.000000
25%          4.000000
50%          6.000000
75%          9.000000
max         12.000000
Name: month, dtype: float64

In [14]:
datanew["day"].describe()

count    31370.000000
mean        15.419828
std         33.205682
min      -5656.000000
25%          8.000000
50%         15.000000
75%         23.000000
max         31.000000
Name: day, dtype: float64

In [15]:
datanew["hour"].describe()

count    31370.000000
mean        11.290755
std         37.212010
min      -6464.000000
25%          5.000000
50%         11.000000
75%         18.000000
max         23.000000
Name: hour, dtype: float64

In [16]:
datanew["PM2.5"].describe()

count    3.137000e+04
mean     2.104689e+03
std      3.583226e+05
min      3.000000e+00
25%      2.300000e+01
50%      5.800000e+01
75%      1.120000e+02
max      6.346466e+07
Name: PM2.5, dtype: float64

In [17]:
# Finding outlier-
new_list = []
for i in datanew["PM2.5"]:
    if i >900.0:
        new_list.append(i)
print(new_list)

[63464664.0]

In [18]:
datanew["temperature"].describe()

count    31370.000000
mean        14.387564
std         11.292983
min        -16.800000
25%          4.400000
50%         15.900000
75%         23.700000
max         40.500000
Name: temperature, dtype: float64

In [19]:
datanew["pressure"].describe()

count     31370
unique      563
top        1019
freq        213
Name: pressure, dtype: object

In [20]:
#Converting to numeric
col_pressure = pd.to_numeric(datanew["pressure"])

In [21]:
col_pressure

2        1023.5
3        1024.5
4        1025.2
6        1026.5
7        1027.4
          ...
31522    1019.4
31523    1014.0
31524    1014.1
31525    1016.0
31526    1013.3
Name: pressure, Length: 31370, dtype: float64

In [22]:
col_pressure.describe()

count    31370.000000
mean      1010.778689
std         38.949575
min      -5646.000000
25%       1002.700000
50%       1010.200000
75%       1019.000000
max       1042.000000
Name: pressure, dtype: float64

In [23]:
# Finding outlier-
new_list = []
for i in col_pressure:
    if i < 900.0:
        new_list.append(i)
print(new_list)

[-5646.0]

In [24]:
datanew["rain"].describe()

count    31370.000000
mean         0.072072
std          0.951900
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max         72.500000
Name: rain, dtype: float64

In [25]:
datanew["wind_direction"].describe()

count     31370
unique       16
top          NE
freq       4455
Name: wind_direction, dtype: object

In [26]:
datanew["wind_speed"].describe()

count    31370.000000
mean         1.697367
std          1.337670
min        -79.000000
25%          0.900000
50%          1.400000
75%          2.200000
max         11.200000
Name: wind_speed, dtype: float64

In [27]:
# Finding outlier-
new_list = []
for i in datanew["wind_speed"]:
    if ( i < 0):
        new_list.append(i)
print(new_list)

[-66.0, -79.0]

In [28]:
# Unique values in each column-
for i in datanew:
    print(datanew[i].unique())

[    2     3     4 ... 35035 35042 35054]
['2013' '2014' '2015' '2016' '2017']
[ 3.  4.  5.  6.  7.  8.  9. 10. 11. 12.  1.  2.]
[ 1.000e+00  2.000e+00  3.000e+00  4.000e+00  5.000e+00  6.000e+00
  7.000e+00  8.000e+00  9.000e+00  1.000e+01  1.100e+01  1.200e+01
  1.300e+01  1.400e+01  1.500e+01  1.600e+01  1.700e+01  1.800e+01
  1.900e+01  2.000e+01  2.100e+01  2.200e+01  2.300e+01  2.400e+01
  2.500e+01  2.600e+01  2.700e+01  2.800e+01  2.900e+01  3.000e+01
  3.100e+01 -5.656e+03]
[ 2.000e+00  3.000e+00  4.000e+00  6.000e+00  7.000e+00  8.000e+00
  9.000e+00  1.000e+01  1.200e+01  1.300e+01  1.400e+01  1.500e+01
  1.600e+01  1.700e+01  1.800e+01  2.000e+01  2.100e+01  2.300e+01
  0.000e+00  1.000e+00  5.000e+00  1.100e+01  1.900e+01  2.200e+01
 -6.464e+03]
[7.0000000e+00 6.0000000e+00 3.0000000e+00 8.0000000e+00 9.0000000e+00
 1.0000000e+01 1.1000000e+01 1.2000000e+01 2.4000000e+01 2.2000000e+01
 1.4000000e+01 1.3000000e+01 4.0000000e+00 1.8000000e+01 2.6000000e+01
 2.5000000e+01 3.7000000e+01 4.4000000e+01 5.4000000e+01 6.1000000e+01
 6.7000000e+01 7.4000000e+01 8.1000000e+01 9.3000000e+01 1.1200000e+02
 1.0900000e+02 1.1000000e+02 1.0500000e+02 1.0600000e+02 1.0100000e+02
 9.1000000e+01 7.9000000e+01 7.7000000e+01 8.3000000e+01 9.4000000e+01
 9.6000000e+01 9.8000000e+01 7.2000000e+01 4.8000000e+01 2.8000000e+01
 1.9000000e+01 6.0000000e+01 1.1700000e+02 4.6000000e+01 4.2000000e+01
 4.9000000e+01 3.4000000e+01 1.5000000e+01 1.6000000e+01 2.0000000e+01
 3.1000000e+01 4.0000000e+01 5.1000000e+01 5.8000000e+01 7.1000000e+01
 1.0000000e+02 1.0300000e+02 1.1500000e+02 1.0400000e+02 1.1100000e+02
 1.1400000e+02 1.3100000e+02 1.3800000e+02 1.4200000e+02 1.6300000e+02
 1.6800000e+02 1.6500000e+02 1.6600000e+02 1.9000000e+02 2.0300000e+02
 2.1000000e+02 2.0500000e+02 2.1500000e+02 2.1900000e+02 2.2600000e+02
 2.8400000e+02 2.7200000e+02 2.4200000e+02 2.1200000e+02 1.9200000e+02
 1.8800000e+02 1.8600000e+02 1.9400000e+02 1.8400000e+02 1.7500000e+02
 1.7900000e+02 2.0100000e+02 2.3000000e+02 2.4600000e+02 2.4800000e+02
 2.3900000e+02 2.5400000e+02 2.6600000e+02 2.6000000e+02 2.5000000e+02
 2.4000000e+02 2.3800000e+02 2.4300000e+02 2.7500000e+02 3.0600000e+02
 3.2000000e+02 2.9200000e+02 2.5100000e+02 2.2800000e+02 2.1700000e+02
 2.5500000e+02 2.5800000e+02 2.7700000e+02 2.8200000e+02 2.6700000e+02
 2.1600000e+02 2.1100000e+02 2.2700000e+02 3.6300000e+02 3.7600000e+02
 3.4400000e+02 3.3900000e+02 3.2400000e+02 3.2200000e+02 3.1500000e+02
 3.1000000e+02 3.2600000e+02 1.2100000e+02 3.3000000e+02 1.7200000e+02
 8.2000000e+01 8.4000000e+01 9.0000000e+01 8.9000000e+01 9.7000000e+01
 1.0200000e+02 1.0800000e+02 1.1300000e+02 1.4500000e+02 6.9000000e+01
 7.8000000e+01 4.7000000e+01 2.1000000e+01 1.7000000e+01 2.7000000e+01
 3.0000000e+01 3.6000000e+01 3.8000000e+01 7.0000000e+01 6.4000000e+01
 9.5000000e+01 1.2000000e+02 1.4100000e+02 1.4000000e+02 1.4900000e+02
 1.5000000e+02 1.3200000e+02 1.4400000e+02 1.5600000e+02 1.7400000e+02
 1.5200000e+02 1.2500000e+02 1.4600000e+02 1.1600000e+02 1.2300000e+02
 1.3000000e+02 1.2900000e+02 1.3900000e+02 1.3500000e+02 1.3300000e+02
 1.2400000e+02 1.3700000e+02 1.6000000e+02 8.8000000e+01 5.0000000e+01
 2.3000000e+01 3.5000000e+01 6.2000000e+01 6.5000000e+01 7.3000000e+01
 1.1900000e+02 1.6200000e+02 1.8000000e+02 1.8300000e+02 1.8200000e+02
 1.7300000e+02 1.6400000e+02 2.3600000e+02 2.5600000e+02 2.8700000e+02
 2.7800000e+02 2.6900000e+02 2.8600000e+02 3.0400000e+02 3.1200000e+02
 3.1600000e+02 3.5300000e+02 3.5500000e+02 3.2800000e+02 3.0800000e+02
 3.1400000e+02 2.7600000e+02 2.6400000e+02 2.7000000e+02 1.8500000e+02
 1.9700000e+02 1.7600000e+02 2.0600000e+02 2.5700000e+02 2.9300000e+02
 2.9400000e+02 3.3200000e+02 3.5200000e+02 3.6200000e+02 3.5600000e+02
 3.5700000e+02 3.6400000e+02 3.9200000e+02 4.2300000e+02 4.3400000e+02
 4.5000000e+02 4.6300000e+02 5.5000000e+01 3.3000000e+01 2.9000000e+01
 3.2000000e+01 5.9000000e+01 4.5000000e+01 5.2000000e+01 3.9000000e+01
 6.8000000e+01 4.1000000e+01 9.2000000e+01 1.7800000e+02 1.8100000e+02
 1.8700000e+02 2.0200000e+02 5.6000000e+01 7.5000000e+01 6.6000000e+01
 7.6000000e+01 5.3000000e+01 8.0000000e+01 8.6000000e+01 6.3000000e+01
 5.0000000e+00 4.3000000e+01 1.1800000e+02 2.0900000e+02 2.2000000e+02
 2.2300000e+02 2.1400000e+02 2.0000000e+02 1.9900000e+02 2.0400000e+02
 2.2200000e+02 2.2900000e+02 1.4300000e+02 1.2800000e+02 2.2100000e+02
 1.5900000e+02 5.7000000e+01 1.5100000e+02 2.2500000e+02 2.3500000e+02
 2.3300000e+02 1.2600000e+02 1.6100000e+02 1.3600000e+02 1.3400000e+02
 1.4700000e+02 1.5400000e+02 1.5300000e+02 1.5700000e+02 2.0800000e+02
 1.2200000e+02 8.5000000e+01 6.3464664e+07 9.9000000e+01 1.0700000e+02
 1.2700000e+02 8.7000000e+01 1.7100000e+02 1.8900000e+02 1.9800000e+02
 2.3200000e+02 2.6300000e+02 2.3700000e+02 1.6900000e+02 1.9300000e+02
 1.9500000e+02 3.6600000e+02 1.7000000e+02 2.5200000e+02 2.6200000e+02
 2.7900000e+02 2.8800000e+02 2.7300000e+02 3.1100000e+02 3.0300000e+02
 1.6700000e+02 6.6500000e+02 1.5800000e+02 1.4800000e+02 1.5500000e+02
 2.1800000e+02 1.9100000e+02 1.7700000e+02 2.0700000e+02 2.4700000e+02
 3.6800000e+02 3.1700000e+02 2.4900000e+02 4.6400000e+02 4.9400000e+02
 4.8500000e+02 5.1000000e+02 4.3000000e+02 2.8100000e+02 2.7100000e+02
 2.4500000e+02 2.2400000e+02 2.1300000e+02 2.5300000e+02 2.3400000e+02
 2.6500000e+02 2.8300000e+02 2.9000000e+02 2.9700000e+02 3.2100000e+02
 2.9500000e+02 2.8000000e+02 3.4000000e+02 3.4900000e+02 3.3400000e+02
 2.8900000e+02 3.0500000e+02 2.6100000e+02 3.4500000e+02 3.2700000e+02
 3.1300000e+02 3.0200000e+02 1.9600000e+02 2.7400000e+02 2.3100000e+02
 2.4400000e+02 3.4200000e+02 3.6700000e+02 3.0700000e+02 2.4100000e+02
 3.6100000e+02 3.4100000e+02 2.8500000e+02 3.0000000e+02 3.8800000e+02
 3.8500000e+02 3.7800000e+02 3.7100000e+02 4.1300000e+02 4.2000000e+02
 3.3500000e+02 3.5000000e+02 3.2300000e+02 3.3700000e+02 3.3100000e+02
 2.9600000e+02 4.0200000e+02 2.5900000e+02 4.3600000e+02 4.7200000e+02
 4.9900000e+02 5.1100000e+02 5.3000000e+02 5.3800000e+02 5.3500000e+02
 5.2100000e+02 4.7500000e+02 3.9800000e+02 3.8300000e+02 3.8900000e+02
 3.9600000e+02 4.1800000e+02 4.2200000e+02 3.3300000e+02 2.9800000e+02
 3.4300000e+02 4.8100000e+02 5.0100000e+02 5.8400000e+02 5.2500000e+02
 4.6100000e+02 4.1400000e+02 4.5500000e+02 5.0500000e+02 4.6600000e+02
 4.0100000e+02 4.0300000e+02 4.1200000e+02 5.0300000e+02 5.0000000e+02
 4.8800000e+02 4.7800000e+02 4.5600000e+02 4.3500000e+02 4.2500000e+02
 4.0700000e+02 3.5800000e+02 3.7900000e+02 3.7500000e+02 2.6800000e+02
 2.9100000e+02 2.9900000e+02 3.2500000e+02 3.7700000e+02 4.2700000e+02
 4.1600000e+02 3.9400000e+02 3.4600000e+02 4.8300000e+02 4.8900000e+02
 4.2600000e+02 4.4500000e+02 4.4000000e+02 5.1800000e+02 4.9800000e+02
 3.1900000e+02 3.1800000e+02 3.0100000e+02 3.7400000e+02 3.7000000e+02
 4.1000000e+02 3.5400000e+02 8.7800000e+01 8.4600000e+01 8.5600000e+01
 2.2560000e+02 2.6800000e+01 1.0230000e+02 1.1360000e+02 7.8300000e+01
 8.1300000e+01 3.8100000e+02 3.9300000e+02 3.8400000e+02 3.3600000e+02
 3.3800000e+02 4.4600000e+02 3.5100000e+02 3.0900000e+02 3.2900000e+02
 3.6000000e+02 4.3200000e+02 4.3100000e+02 4.0900000e+02 8.6000000e+00
 4.0400000e+02 4.1900000e+02 4.1100000e+02 3.4700000e+02 3.6500000e+02
 3.9000000e+02 4.0800000e+02 4.9700000e+02 4.6900000e+02 4.3800000e+02
 3.9900000e+02 1.1410000e+02 6.6200000e+01 6.7500000e+01 3.9700000e+02
 3.5900000e+02 3.8000000e+02 3.6900000e+02 4.9200000e+02 6.1900000e+02
 6.1800000e+02 6.0600000e+02 5.8300000e+02 5.9800000e+02 6.1200000e+02
 5.8700000e+02 5.6500000e+02 5.4200000e+02 4.3900000e+02 4.4400000e+02
 4.5300000e+02 5.5200000e+02 4.7300000e+02 5.2900000e+02 5.5000000e+02
 6.0700000e+02 6.0400000e+02 5.6900000e+02 5.7700000e+02 4.7000000e+02
 4.8700000e+02 5.0700000e+02 4.0500000e+02 5.8600000e+02 6.2700000e+02
 6.4600000e+02 6.4400000e+02 6.5700000e+02 6.3500000e+02 5.4600000e+02
 4.7600000e+02 4.7700000e+02 4.8000000e+02 4.7900000e+02 4.6700000e+02
 4.2800000e+02 5.2700000e+02 5.2300000e+02 3.8200000e+02 5.1900000e+02
 8.9800000e+02 7.1300000e+02 6.1500000e+02 5.8500000e+02 5.4400000e+02
 3.4800000e+02 4.3300000e+02 4.0600000e+02 3.8600000e+02 3.9500000e+02
 5.2200000e+02 4.1700000e+02 4.2900000e+02]
[ -1.1         -1.4         -2.          -2.6         -1.6
   0.1          1.2          1.9          3.9          5.3
   6.           6.2          5.9          4.3          3.1
   1.7          0.6         -0.2         -0.4         -1.
  -1.5         -1.8         -2.5         -1.7          2.2
   2.7          3.3          3.8          3.5          1.5
  -0.6         -0.8         -2.8         -4.3         -5.6
  -5.8         -3.1          0.7          6.5         11.4
  13.8         16.          16.7         16.9         16.4
  13.1          8.7         12.2         11.7          5.2
   7.7          8.2          8.1          7.2          9.
  10.6         11.9         14.2         15.3         15.2
  14.5         12.7         11.6         10.9          9.9
   8.4          8.6          4.7          1.1          0.2
   1.8          2.9          5.1          9.4         12.6
  13.5         13.2         12.1          4.9          4.8
   4.1          4.           4.5          5.7          6.6
   7.5         10.1         11.1         14.7          6.8
   4.4          2.4          2.3          0.3         -0.9
   1.6          8.3         16.5         17.1         17.7
  18.3         18.6         17.9         15.4         14.4
  13.4         11.8          9.2          2.5          1.3
   1.4         19.1         20.5         21.7         22.5
  17.4         13.9         10.3          9.3          8.
   7.9          6.3          3.6          2.1          3.2
   2.8          4.6         16.3         14.3         12.4
  10.5         10.2          7.4          6.4          5.6
   0.8         -0.5         -2.1         -1.3          9.8
  10.4         11.2         11.3          9.1          3.
  -0.7         -2.3          6.7          7.6          9.7
  10.7          9.6          3.4          3.7          5.8
   5.5          8.5          9.5          7.1          6.1
   5.          -0.1          0.5          2.           1.
   4.2         12.          12.3         11.5          7.
   7.3         14.          14.1         13.6         12.9
  10.8         10.           7.8         15.1         15.9
  15.5          8.8          5.4          2.6          0.4
   0.9         -0.3         -1.2         -5.7          6.9
   8.9         12.8         12.5         17.2         19.5
  18.9         18.2         15.7         16.1         14.6
   0.          16.6         17.5         18.          19.6
  15.6         13.          11.          14.9         13.3
  17.          18.1         19.2         20.9         22.6
  22.2         21.6         20.7         19.7         18.4
  24.4         26.1         24.2         25.2         24.6
  24.          23.          21.1         16.2         20.2
  20.8         22.          21.9         15.8         15.
  14.8         17.3         17.6         13.7         24.1
  23.3         21.5         20.4         18.8         17.8
  19.          20.1         22.7         24.3         23.6
  23.7         20.6         21.8         23.1         23.4
  23.8         23.9         20.3         19.3         19.9
  24.5         25.5         26.7         27.6         28.9
  28.7         28.5         27.9         25.4         27.
  27.4         29.          29.1         28.2         24.8
  21.4         22.4         21.3         20.          19.4
  21.2         23.5         22.9         18.5         22.3
  22.8         21.          23.2         25.7         26.8
  27.3         27.1         26.4         16.8         25.3
  28.3         30.6         30.9         30.5         29.7
  28.6         26.9         29.4         25.8         24.9
  18.7         22.1         19.8         25.          26.3
  29.3         30.1         31.          30.3         26.6
  31.2         32.1         32.8         32.7         33.
  31.9         25.1         28.4         29.2         30.
  27.5         30.7         26.2         28.          25.9
  24.7         25.6         28.1         27.2         27.7
  26.5         29.5         29.8         29.6         30.4
  32.2         33.4         33.7         33.3         26.
  30.8         30.2         29.9         32.9         33.1
  28.8         27.8         31.5         31.6         32.
  31.1         31.3         32.5         34.          34.8
  35.4         34.4         31.7         32.6         33.5
  34.2         33.8         35.3         36.1         36.
  35.5         34.9         34.3         35.1         36.4
  36.8         36.7         31.8         33.6         34.6
  35.7         37.2         36.2         33.9         32.4
  33.2         31.4         35.2         37.1         37.6
  37.9         37.4         36.9         35.9         34.7
  35.8         32.3         35.          36.3         34.1
  34.5         35.6         -1.9         -2.9         -3.2
  -3.3         -2.2         -3.4         -2.4         -3.5
  -2.7         -3.9         -4.1         -3.6         -3.
  -4.4         -3.7         -4.8         -5.2         -5.3
  -4.7         -4.6         -3.8         -4.9         -4.2
  -4.          -5.5         -5.9         -6.4         -6.9
  -5.          -7.          -7.2         -7.6         -6.
  -7.1         -8.          -6.1         -5.4         -6.5
  -6.6         -6.8         -5.1         -7.4         -7.3
  -7.5         -8.5         -9.2         -8.1         -8.9
  -4.5         -9.4         -7.8         -8.6         -9.
  -9.3         -8.2         -6.7         -6.2         -8.3
  -8.4         -9.1        -10.         -10.2         -6.3
  -7.9         -8.7        -10.3        -11.4        -12.2
 -10.7         -9.5        -10.1         37.8         39.2
  40.5         40.3         40.1         38.1         36.5
  36.6         -7.7          4.66666667   9.33333333   3.85714286
  37.7         38.4         38.3         38.8         38.
  -8.8         -9.6         -9.7        -11.         -11.3
 -11.1        -10.4        -11.5        -12.         -12.5
 -11.2        -12.3        -13.4        -12.9        -14.4
 -15.1        -15.2        -10.9        -10.5        -11.7
 -12.6        -13.1        -14.         -13.8        -14.2
 -14.1        -14.8        -15.6        -16.3        -16.8
 -15.9        -15.3        -15.4        -15.         -15.8
 -16.2        -16.1        -16.         -14.5        -14.3
 -12.1         -9.8         37.          37.3         25.825
  29.35        28.425       27.075       26.675       23.175
  23.025       22.65        22.275       23.325       22.825
  21.55        20.625       20.375       19.775       17.775
  16.75        15.975       18.95        21.675       23.825
  24.425       24.775       20.85        18.05        19.45
  22.075       24.625       25.125       25.35        24.45
  23.65        22.775       22.675       20.825       18.075
  21.475       20.975       21.05        26.825       20.72222222
  18.575       19.425       19.975       20.725       16.25
  16.85        20.225       19.85        17.85        17.225
  15.525       13.85        13.15        13.625       19.025
  20.125       20.525       14.175        9.325        9.175
   9.075        9.625       15.56666667  12.22        11.125
   8.04        11.8125      10.475        5.825        5.575
   8.425       10.56666667  14.86666667  12.15         9.86666667
  10.18        12.325       13.92        11.075       10.46
  10.16666667   9.95         9.74         9.55         8.45
   8.84         0.275       -0.35         0.575       -1.075
   0.06666667   2.825        2.35        -0.525       -1.425
  -5.15        -1.85         2.575        5.625       -0.175
  -0.475       -1.675       -0.25         2.025        3.675
   2.425       -2.15        -1.65         0.075       -1.55
  -4.125       -4.875       -4.95        -1.475        0.75
  -0.575       -2.65        -4.025       -1.06        -3.75
  -3.45        -2.08        -0.15         0.96         0.35
  -0.225       -2.25        -5.4625      -2.96666667   1.63333333
   1.25        -7.425       -7.075       -1.42        -4.85
  -8.225       -2.725       -0.63333333  -0.13333333  -0.34
  -4.975       -8.45        -7.95        -5.975       -4.775
  -3.525       -0.66        -0.925       -3.96666667  -6.275
  -7.275       -1.725       -2.35        -6.96666667  -8.55
  -0.93333333   0.25         1.875       -5.325       -6.975
  -1.625       -3.95        -2.925       -0.06666667   8.375
   4.325        1.725       -1.275       -1.75        -0.875
  -3.375       -1.95         1.475     ]
['1023.5' '1024.5' '1025.2' '1026.5' '1027.4' '1028.3' '1028.5' '1028.2'
 '1027.3' '1026.2' '1025.9' '1025.7' '1025.6' '1026.3' '1029.1' '1030.1'
 '1030.5' '1031' '1031.3' '1030.9' '1030.6' '1030.8' '1029.6' '1029.8'
 '1029.7' '1028.9' '1024.8' '1024.1' '1023.6' '1023.4' '1023.2' '1022.9'
 '1022.6' '1022.3' '1021.1' '1020.4' '1019.4' '1018.3' '1017.2' '1016.9'
 '1016.3' '1016.2' '1016.5' '1015.8' '1014.9' '1013.8' '1012.5' '1011.5'
 '1010.8' '1010.5' '1010.6' '1011.1' '1012.3' '1013.4' '1013.5' '1013.6'
 '1014.1' '1014.8' '1015.7' '1016.7' '1018' '1018.6' '1018.9' '1019.7'
 '1020.7' '1020.8' '1020' '1017.8' '1017' '1015.9' '1016.6' '1015.2'
 '1014.7' '1014.4' '1014' '1013.7' '1013.9' '1012.8' '1012' '1009.7'
 '1008.5' '1007.7' '1007.2' '1007.1' '1008.2' '1008.7' '1009' '1008.9'
 '1008.4' '1008.3' '1007.8' '1007.6' '1007.3' '1009.3' '1009.1' '1008.6'
 '1006.9' '1005.8' '1005.5' '1005.9' '1006.8' '1006.5' '1006.4' '1006.7'
 '1006.6' '1006.1' '1003.6' '1001.6' '1000.2' '998.6' '997.6' '997.2'
 '997.1' '997.4' '997.9' '997.7' '998.3' '998.4' '998.2' '998.5' '999'
 '999.7' '1000.8' '1001.1' '1000.9' '1000.5' '999.4' '999.5' '999.9'
 '1000.6' '1000.4' '1000' '996.1' '994.9' '994.1' '993' '992' '992.2'
 '992.9' '995.9' '1001.3' '1004.3' '1008.1' '1009.4' '1013' '1018.1'
 '1020.3' '1021.2' '1021.3' '1020.9' '1021.9' '1022' '1023.1' '1022.4'
 '1021' '1019' '1018.7' '1018.2' '1018.5' '1018.8' '1017.4' '1017.5'
 '1016.8' '1016' '1015' '1010.9' '1010.3' '1009.5' '1009.8' '1010'
 '1010.4' '1009.2' '1008' '1007.5' '1006.3' '1006.2' '1015.5' '1017.7'
 '1019.3' '1020.5' '1022.2' '1023.3' '1024.6' '1024.4' '1023.7' '1021.7'
 '1022.8' '1024' '1023.8' '1024.2' '1023.9' '1024.3' '1024.9' '1018.4'
 '1016.1' '1015.1' '1014.2' '1013.2' '1011.9' '1011.4' '1011.6' '1012.2'
 '1015.3' '1015.6' '1020.1' '1020.2' '1019.9' '1014.6' '1012.6' '1011.2'
 '1008.8' '1007.9' '1006' '1005.3' '1004.7' '1001.9' '1000.1' '998.7'
 '997.5' '996.6' '996.2' '996.3' '996' '996.4' '999.8' '1001.4' '1002.4'
 '1003.2' '1003.5' '1004.2' '1002.1' '1002.9' '1003.7' '1004' '1004.9'
 '1005.4' '1007' '1007.4' '1016.4' '1019.6' '1014.5' '1012.7' '1011.8'
 '1011.3' '1009.6' '1004.5' '1003' '1002.5' '1004.4' '1010.1' '1010.7'
 '1012.9' '1010.2' '1011' '1011.7' '1005.2' '1004.8' '1003.8' '1003.4'
 '1017.3' '1017.6' '1019.5' '1013.1' '1004.1' '1005' '1002.8' '1002.2'
 '1003.3' '1004.6' '1003.9' '1017.1' '1013.3' '1014.3' '1017.9' '1009.9'
 '1012.4' '1005.6' '1005.7' '1012.1' '1005.1' '1002.7' '996.9' '1001.2'
 '1003.1' '1015.4' '1002.3' '999.6' '996.5' '996.7' '996.8' '998.1'
 '998.8' '1000.7' '1000.3' '999.3' '999.2' '998.9' '997.3' '997' '995.6'
 '994.5' '994.2' '994.8' '995.5' '1001.8' '1002' '1001.7' '1019.1'
 '1019.2' '1021.6' '1001' '998' '997.8' '995.2' '993.4' '992.8' '992.6'
 '993.6' '994.3' '994' '993.9' '993.1' '991.6' '991' '990.6' '990.4'
 '990.1' '990' '989.4' '989.1' '989' '988.8' '988.3' '988.1' '988' '990.2'
 '991.2' '992.3' '992.1' '992.4' '992.5' '993.3' '994.7' '995.4' '995.1'
 '995.7' '993.5' '995' '993.8' '994.4' '1002.6' '992.7' '993.7' '995.8'
 '991.7' '991.4' '991.9' '991.8' '991.5' '990.9' '990.3' '990.5' '993.2'
 '999.1' '995.3' '1001.5' '994.6' '989.7' '989.2' '989.5' '989.9' '988.7'
 '989.3' '991.3' '990.7' '991.1' '990.8' '989.6' '989.8' '988.9' '988.6'
 '987.2' '986.3' '985.9' '1022.7' '1026.9' '1027.5' '1027.7' '1028.1'

In [29]:
datanew

,Unnamed: 0,year,month,day,hour,PM2.5,temperature,pressure,rain,wind_direction,wind_speed
2,2,2013,3.0,1.0,2.0,7.0,-1.1,1023.5,0.0,NNW,5.6
3,3,2013,3.0,1.0,3.0,6.0,-1.4,1024.5,0.0,NW,3.1
4,4,2013,3.0,1.0,4.0,3.0,-2.0,1025.2,0.0,N,2.0
6,6,2013,3.0,1.0,6.0,3.0,-2.6,1026.5,0.0,NNE,2.5
7,7,2013,3.0,1.0,7.0,3.0,-1.6,1027.4,0.0,NNW,3.8
...,...,...,...,...,...,...,...,...,...,...,...
31522,35022,2017,2.0,27.0,6.0,80.0,-0.3,1019.4,0.0,ENE,0.8
31523,35032,2017,2.0,27.0,16.0,75.0,15.9,1014,0.0,SW,2.9
31524,35035,2017,2.0,27.0,19.0,51.0,11.5,1014.1,0.0,SSW,1.0
31525,35042,2017,2.0,28.0,2.0,9.0,8.6,1016,0.0,NNE,0.9
31526,35054,2017,2.0,28.0,14.0,5.0,14.6,1013.3,0.0,N,3.6

Removing all rows which contain outliers-

In [33]:
indexNames = datanew[ (datanew['day'] < 0.0) ].index
datanew.drop(indexNames , inplace=True)
indexNames = datanew[ (datanew['hour'] < 0.0) ].index
datanew.drop(indexNames , inplace=True)
indexNames = datanew[ (datanew['PM2.5'] > 900.0) ].index
datanew.drop(indexNames , inplace=True)
indexNames = datanew[ (datanew['wind_speed'] < 0.0) ].index
datanew.drop(indexNames , inplace=True)
datanew

,Unnamed: 0,year,month,day,hour,PM2.5,temperature,pressure,rain,wind_direction,wind_speed
2,2,2013,3.0,1.0,2.0,7.0,-1.1,1023.5,0.0,NNW,5.6
3,3,2013,3.0,1.0,3.0,6.0,-1.4,1024.5,0.0,NW,3.1
4,4,2013,3.0,1.0,4.0,3.0,-2.0,1025.2,0.0,N,2.0
6,6,2013,3.0,1.0,6.0,3.0,-2.6,1026.5,0.0,NNE,2.5
7,7,2013,3.0,1.0,7.0,3.0,-1.6,1027.4,0.0,NNW,3.8
...,...,...,...,...,...,...,...,...,...,...,...
31522,35022,2017,2.0,27.0,6.0,80.0,-0.3,1019.4,0.0,ENE,0.8
31523,35032,2017,2.0,27.0,16.0,75.0,15.9,1014,0.0,SW,2.9
31524,35035,2017,2.0,27.0,19.0,51.0,11.5,1014.1,0.0,SSW,1.0
31525,35042,2017,2.0,28.0,2.0,9.0,8.6,1016,0.0,NNE,0.9
31526,35054,2017,2.0,28.0,14.0,5.0,14.6,1013.3,0.0,N,3.6

Since the field "Pressure" has neither int or float dataype we will remove its 'one' outlier that we found seperately ( by index at which the outlier is present) -

In [35]:
updated_data = datanew.drop(24314,axis=0)

In [36]:
#checking if the outlier has been removed
col_pressure = pd.to_numeric(updated_data["pressure"])
col_pressure.describe()

count    31364.000000
mean      1010.989398
std         10.217321
min        985.900000
25%       1002.700000
50%       1010.200000
75%       1019.000000
max       1042.000000
Name: pressure, dtype: float64

Now the final dataframe after cleaning is updated_data

In [37]:
updated_data

,Unnamed: 0,year,month,day,hour,PM2.5,temperature,pressure,rain,wind_direction,wind_speed
2,2,2013,3.0,1.0,2.0,7.0,-1.1,1023.5,0.0,NNW,5.6
3,3,2013,3.0,1.0,3.0,6.0,-1.4,1024.5,0.0,NW,3.1
4,4,2013,3.0,1.0,4.0,3.0,-2.0,1025.2,0.0,N,2.0
6,6,2013,3.0,1.0,6.0,3.0,-2.6,1026.5,0.0,NNE,2.5
7,7,2013,3.0,1.0,7.0,3.0,-1.6,1027.4,0.0,NNW,3.8
...,...,...,...,...,...,...,...,...,...,...,...
31522,35022,2017,2.0,27.0,6.0,80.0,-0.3,1019.4,0.0,ENE,0.8
31523,35032,2017,2.0,27.0,16.0,75.0,15.9,1014,0.0,SW,2.9
31524,35035,2017,2.0,27.0,19.0,51.0,11.5,1014.1,0.0,SSW,1.0
31525,35042,2017,2.0,28.0,2.0,9.0,8.6,1016,0.0,NNE,0.9
31526,35054,2017,2.0,28.0,14.0,5.0,14.6,1013.3,0.0,N,3.6

In [38]:
updated_data.to_csv('updated_data.csv', index=False)